my_theme:
    resource: "@MyThemeBundle/Resources/config/routing.yml"
    prefix:   /

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# https://stackoverflow.com/a/50494919
# for FOSUserBundle >= 2.1
#fos_user_profile_show:
#    path: /profile
#    methods: AppBundle\Controller\ProfileController::showAction

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#fos_user_register:
    #resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    #prefix: /register

avanzu_admin_home:
    path: /profile
    defaults: {_controller: AvanzuAdminThemeBundle:Default:index}
    options:
        avanzu_admin_route: welcome

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"